### ISSUE TITLE
Pairing a second bluetooth device

### ISSUE THREAD

**Issue by a-singer** [rosmo/go-hidproxy#2]
Hello,

	Let me first thank you for an amazingly useful program. I am using it to type on a keyboard which I was about to throw away because it wouldn't properly connect to an old machine. Now that I can make the keyboard look like a HID device, things are working perfectly. I should also say that the low latency is really appreciated. I have two questions, the first being in this issue and the second in a later one. I wish to pair a second device with the Pi0 and have that second device proxied. Is this possible, or is only one device usable? If a second device is usable, can I reboot the Pi0, connect it to an ethernet cable, SSH into it, and pair the second device? That is, now that the proxy starts whenever the machine boots, can I still use a USB ethernet adapter on the HID port, or will it no longer work because the proxy is expecting to see a USB host on the HID port?

Thanks again,

**Comment by rosmo** [comment]
Sounds great! I'm actually using the Wifi on the device, so I can leave the USB port free to connect to the host device. But the way you describe it should work just fine. Bluetooth pairings are stored over reboots and should automatically connect.

The go-hidproxy itself has been built to support as many devices as you can connect (both keyboards and mice), but admittedly I haven't spent too much time testing that feature.

**Comment by a-singer** [comment]
This is really good, I have some devices here which are either unique or almost unique, and this will give them a new lease on life. Thanks again for your time in producing this.
